improved version of Pr 15 delete button
JulioLaplace/calendar_app pull request #17
Opened 2024-10-22 00:54 UTC by CN-Discretemathematics

2024-10-22 20:27 UTC, abhiram54 approved these changes

2024-10-23 12:39 UTC, EnguerrandINSA commented on src/Services/eventService.js
Why did you change the deleteEventFromFirestore function ? Because it doesn't work for me. I created a new event, which worked fine. But when I wanted to delete it, I had some errors : "Error deleting event:  TypeError: Cannot read properties of undefined (reading 'indexOf') "

2024-10-23 12:39 UTC, EnguerrandINSA requested changes
I added a comment for the eventService.js file

2024-10-23 13:08 UTC, CN-Discretemathematics commented on src/Services/eventService.js
they are the same actually,i just want to make the codes more clearly,i didn't change the logic so i think the previous one should also worked as well.

2024-10-24 12:16 UTC, merged